`r if (knitr:::is_html_output()) "
# Author's Note {-}
"`

___A Conditional Dinner___ was initially an exercise in attempting to apply the idea of a bottle episode to a short story. Bottle episodes are commonly used in television when budget constraints necesitate an episode that is able to be produced cheaply or quickly, often meaning the entire episode is restricted to a single set and core cast members. Some famous examples include Friends’ *The One Where No One’s Ready*, Breaking Bad’s *Fly*, and Seinfeld’s *The Chinese Restaurant*. An additional use of bottle episodes is to focus in on characterization and explore traits and motives. I found this to translate nicely to this piece, which was already placed under certain constraints- a word bank, a certain page length, and the requirement to create some type of full story arc. To go along with the theme, I wanted the cast of characters to feel like an ensemble that could be part of a sitcom, yet be able to focus in on the thoughts of one specific character, in this case our unnamed narrator who serves as the “anchor” comedic archetype. The inspiration for the premise was the aforementioned Seinfeld episode, although any other similarities are purely coincidental as I haven’t seen the actual episode (for shame!). 

Stylistically I would say the piece was heavily influenced by the first half of JD Salinger’s *Raise High the Roof Beam, Carpenters*, in which an ecclectic cast of characters are sandwiched in a car that is stuck in traffic in an attempt to make their way to a wedding reception. There is something compelling about the Salinger type of narrator that we want to dislike, but deep down probably have more in common with than we’d like to admit. In keeping with the sitcom-y feel, I wanted to make sure there were both layered and overt jokes in the piece as well as some absurdity. As a reader or viewer, I like having to work a little bit for a laugh as it makes me feel like I am in on a private joke with the creators. It wasn’t until after I finished the first draft that I realized what I had actually created: a story about a man who has spent so much time eavesdropping on his neighbors’ arguing from his kitchen that his stomach has been conditioned to associate the bickering with his next meal.

